home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),

]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from order import views as orderviews
from home import views

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('product/', include('product.urls')),
    path('order/', include('order.urls')),
    path('user/', include('user.urls')),
    path('home/', include('home.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('hakkimizda/', views.hakkimizda, name='hakkimizda'),
    path('referanslar/', views.referanslar, name='referanslar'),
    path('iletisim/', views.iletisim, name='iletisim'),
    path('products/', views.products, name='products'),
    path('category/<int:id>/<slug:slug>/', views.category_products, name='category_products'),
    path('product/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('search/', views.product_search, name='product_search'),
    #Viewleri görmesinin sebebi home view import edilmesi
    path('search_auto/', views.product_search_auto, name='product_search_auto'),
    path('logout/', views.logout_view, name='logout_view'),
    path('login/', views.login_view, name='login_view'),
    path('signup/', views.signup_view, name='signup_view'),
    path('shopcart/', orderviews.shopcart, name='shopcart'),
    path('sss/', views.faq, name='faq'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from order import views

urlpatterns = [
    path('', views.index, name='index'),
    path('addtocart/<int:id>', views.addtocart, name='addtocart'),
    path('deletefromcart/<int:id>', views.deletefromcart, name='deletefromcart'),
    path('orderproduct/', views.orderproduct, name='orderproduct'),

]

order/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db import models
from django.forms import ModelForm
from product.models import Product

class ShopCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField() #Kac adet olacagı

    def __str__(self):
        return self.product.title

    @property
    def amount(self):
        return (self.quantity * self.product.price)

    @property
    def price(self):
        return (self.product.price) #Amount ve price degerleri de cagrılabilir bu sekilde yazılan fonksiyon ile

class ShopCartForm(ModelForm):
    class Meta:
        model = ShopCart
        fields = ['quantity']

class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Preaparing', 'Preaparing'),
        ('Completed', 'Completed'),
        ('Canceled', 'Canceled'),
    )

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    code = models.CharField(max_length=5, editable=False)
    first_name = models.CharField(max_length=10)
    last_name = models.CharField(max_length=10)
    masa_no = models.IntegerField()
    total = models.FloatField()
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    adminnote = models.CharField(blank=True, max_length=100)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.first_name

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'masa_no']

class OrderProduct(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Canceled', 'Canceled'),
    )

    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price  = models.FloatField()
    amount = models.FloatField()
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.title

order/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.utils.crypto import get_random_string

from home.models import UserProfile, Setting
from order.models import ShopCartForm, ShopCart, OrderForm, Order, OrderProduct
from product.models import Category, Product


def index(request):
    return HttpResponse("Order App")


@login_required(login_url='/login') #lgin olması gerekli
def addtocart(request, id):
    url = request.META.get('HTTP_REFERER')
    current_user = request.user
    checkProduct = ShopCart.objects.filter(product_id=id)
    #****Urun sepette var mı yok mu*******
    if checkProduct:
        control = 1
    else:
        control = 0
    if request.method == 'POST':
        form = ShopCartForm(request.POST)
        if form.is_valid():

            if control == 1: #ürün varsa guncelle
                data = ShopCart.objects.get(product_id=id)
                data.quantity += form.cleaned_data['quantity']
                data.save()
            else: #urun yoksa ekle
                data = ShopCart()
                data.user_id = current_user.id
                data.product_id = id
                data.quantity = form.cleaned_data['quantity']
                data.save()
            request.session['cart_items'] = ShopCart.objects.filter(user_id=current_user.id).count() #sepetteki ürünlerin sayısını alıyoruz
            messages.success(request, "Ürün basarılı bir şekilde eklenmiştir")
            return HttpResponseRedirect(url)

    else: #eger post işlemi yoksa sadece id ile gönderim varsa
        if control == 1:
            data = ShopCart.objects.get(product_id=id)
            data.quantity += 1
            data.save()
        else:
            data = ShopCart()
            data.user_id = current_user.id
            data.product_id = id
            data.quantity = 1
            data.save()
        request.session['cart_items'] = ShopCart.objects.filter(user_id=current_user.id).count()  # sepetteki ürünlerin sayısını alıyoruz
        messages.warning(request, "Ürün sepete eklemede hata oluştu.Lütfen tekrar deneyiniz")
        return HttpResponseRedirect(url)

@login_required(login_url = '/login') #login olması gerekli
def shopcart(request):
    setting = Setting.objects.get(pk=2)
    category = Category.objects.all()
    current_user = request.user
    schopcart = ShopCart.objects.filter(user_id=current_user.id)
    request.session['cart_items'] = ShopCart.objects.filter(user_id=current_user.id).count()  # sepetteki ürünlerin sayısını alıyoruz
    total = 0
    for rs in schopcart:
        total += rs.product.price * rs.quantity

    context = { 'schopcart': schopcart,
                'category': category,
                'total' : total,
                'setting': setting}
    return render(request, 'Shopcart_products.html', context)


@login_required(login_url = '/login') #lgin olması gerekli
def deletefromcart(request,id):
    ShopCart.objects.filter(id=id).delete()
    current_user = request.user
    request.session['cart_items'] = ShopCart.objects.filter( user_id=current_user.id).count()  # sepetteki ürünlerin sayısını alıyoruz
    messages.success(request,"Ürün basarılı bir sekilde silinmiştir")
    return HttpResponseRedirect("/shopcart")


@login_required(login_url = '/login') #lgin olması gerekli
def orderproduct(request):
    setting = Setting.objects.get(pk=2)
    category = Category.objects.all()
    current_user = request.user
    schopcart = ShopCart.objects.filter(user_id = current_user.id)
    total = 0
    for rs in schopcart:
        total += rs.product.price * rs.quantity
    if request.method == 'POST':
        form = OrderForm(request.POST)

        if form.is_valid():
            data = Order()
            data.first_name = form.cleaned_data['first_name']
            data.last_name = form.cleaned_data['last_name']
            data.masa_no = form.cleaned_data['masa_no']
            data.user_id = current_user.id
            data.total = total
            data.ip = request.META.get('REMOTE_ADDR')
            ordercode = get_random_string(5).upper()
            data.code = ordercode
            data.save()

            schopcart = ShopCart.objects.filter(user_id = current_user.id)
            for rs in schopcart:
                detail = OrderProduct()
                detail.order_id = data.id
                detail.product_id = rs.product_id
                detail.user_id = current_user.id
                detail.quantity = rs.quantity

                product = Product.objects.get(id = rs.product_id)
                product.amount -= rs.quantity
                product.save()

                detail.price = rs.product.price
                detail.amount = rs.amount
                detail.save()

            ShopCart.objects.filter(user_id = current_user.id).delete()
            request.session['cart_items'] = 0
            messages.success(request,"Siparisiniz alındı.Teşekürler")
            return render(request,'Order_Complated.html', {'ordercode':ordercode,'category':category})
        else:
            messages.error(request,form.errors)
            return HttpResponseRedirect("/order/orderproduct")

    form = OrderForm()
    profile = UserProfile.objects.get(user_id=current_user.id)
    context = {'schopcart':schopcart,
               'category':category,
               'total':total,
               'form':form,
               'profile':profile,
               'setting': setting
               }
    return render(request,'Order_Form.html',context)

order/templates/Order_Complated.html
{% extends "homebase.html" %}

{% block title %} User {{ user }} {% endblock %}
{% block keywords %} {{ setting.keywords }}  {% endblock %}
{% block descriptions %} {{ setting.description }} {% endblock %}
{% load static %}

{% block head %}
    <link rel = 'shortcut icon' type = 'images/icon.jpeg' href = '{{setting.icon.url}}' />
{% endblock %}

{% block slider %}
    {% include 'slider.html' %}
{% endblock %}

{% block content %}

<section class="story-area left-text center-sm-text mt-50" >
    <div class="heading">
            <img class="heading-img mt-50" src="{% static 'images/heading_logo.png' %}" alt="">
    </div>



<section class="story-area center-text center-sm-text pt-0">
        <div class="container">
            <div class="center-text m-50">
                <p class=""><b>Siparisiniz Alındı</b></p>
            </div><!-- row -->
            <div class="center-text m-50">
                <a href="/" class="btn-primaryc secondary plr-50 mlr-5 mb-10"><b>ANASAYFA</b></a>
            </div>

        </div><!-- container -->
</section>

</section>
{% endblock %}

order/templates/Order_Form.html
{% extends "homebase.html" %}

{% block title %} User {{ user }} {% endblock %}
{% block keywords %} {{ setting.keywords }}  {% endblock %}
{% block descriptions %} {{ setting.description }} {% endblock %}
{% load static %}

{% block head %}
    <link rel = 'shortcut icon' type = 'images/icon.jpeg' href = '{{setting.icon.url}}' />
{% endblock %}

{% block slider %}
    {% include 'slider.html' %}
{% endblock %}

{% block content %}
<div class="mt-50">
<section class="story-area left-text center-sm-text mt-50" >
    <div class="heading">
            <img class="heading-img mt-50" src="{% static 'images/heading_logo.png' %}" alt="">
    </div>
    <h3 class="font-9 mt-10 ml-40 ">
        <ul class="row">
            <li><a href="/">ANASAYFA>> </a></li>
            <li><a href="/shopcart">Order>> </a></li>
            <li class="active">Order Form</li>
        </ul>
    </h3 >
    <hr>



<section class="story-area  center-sm-text pt-0">
        <div class="container">
            <div class="">
                <form action="" method="post">
                    {% csrf_token %}
                    <div>
                        <h4><b>SHIPPING DETAILS</b></h4>
                    </div>
                    <p><label for="id_first_name">First name:</label>
                        <input type="text" name="first_name" value="{{user.first_name}}" class="input" maxlength="10" style="color:black"></p>
                    <p><label for="id_last_name">Last name:</label>
                        <input type="text" name="last_name" value="{{user.last_name}}" class="input" maxlength="10" style="color:black"></p>
                    <p><label for="id_masa_no">Masa No:</label>

                        <input type="text" name="masa_no" value="{{profile.masa_no}}" class="input" maxlength="10" style="color:black"></p>
                    <h6 class="mt-40 center-text"><button type="submit"  class="btn-primaryc plr-40"><b> ORDER</b></button></h6>

                </form>
            </div><!-- row -->
        </div><!-- container -->
</section>
<hr>

<table cellpadding="4" width="1200" height="200" style="margin:30px">
    <tr>
        <th style="color:#EF0031">Image</th>
        <th style="color:#EF0031">Product Name</th>
        <th style="color:#EF0031">Category</th>
        <th style="color:#EF0031">Price</th>
        <th style="color:#EF0031">Amount</th>
        <th style="color:#EF0031">Quantity</th>
    </tr>
    <hr>
    {% for rs in schopcart %}
    <tr>
        <td class=""><a href="/product/{{ rs.id }}/{{ rs.slug }}"><img src="{{rs.product.image.url}}" style="width:90px" > </a></td>
        <td><h4 class=""><a href="/product/{{rs.id}}/{{rs.slug}}">{{rs.product}}</a></h4></td>
        <td><a href="/category/{{rs.category.id}}/{{rs.category.slug}}">{{rs.product.category}}</a></td>
        <td><h4>{{rs.product.price}}TL</h4></td>
        <td><h4>{{rs.quantity}}</h4></td>
        <td><h4>{{rs.amount}}TL</h4></td>
    </tr>

    {% endfor %}
    <tfoot>
        <tr>
            <th class="empty" colspan="4"></th>
            <th>TOTAL</th>
            <th>{{total}}TL</th>
        </tr>

    </tfoot>
</table>



</section>
</div>



{% endblock %}
<style>
#customers {
  font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#customers td, #customers th {
  border: 1px solid #ddd;
  padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #4CAF50;
  color: white;
}
</style>

order/templates/Shopcart_products.html
{% extends "homebase.html" %}
{% load static %}
{% block title %} {{product.title}}{% endblock %}
{% block keywords %} {{ product.keywords }}  {% endblock %}
{% block descriptions %} {{ product.description }} {% endblock %}


{% block head %}
    <link rel = 'shortcut icon' type = 'images/icon.jpeg' href = '{{setting.icon.url}}' />
{% endblock %}

{% block content %}
<section class="story-area left-text center-sm-text" style="margin-top:60px;">
    <h3 class="font-9 mt-30 ml-30  left-text">
        <ul class="row">
            <li><a href="/">ANASAYFA>> </a></li>
            <li class="active">Shopcart</li>
        </ul>
    </h3 >
<table cellpadding="4" width="1200" height="200" style="margin:30px">
    <tr>
        <th style="color:#EF0031">Image</th>
        <th style="color:#EF0031">Product Name</th>
        <th style="color:#EF0031">Category</th>
        <th style="color:#EF0031">Price</th>
        <th style="color:#EF0031">Amount</th>
        <th style="color:#EF0031">Quantity</th>
        <th style="color:#EF0031">Delete</th>
    </tr>
    <hr>
    {% for rs in schopcart %}
    <tr>
        <td class=""><a href="/product/{{ rs.id }}/{{ rs.slug }}"><img src="{{rs.product.image.url}}" style="width:90px" > </a></td>
        <td><h4 class=""><a href="/product/{{rs.id}}/{{rs.slug}}">{{rs.product}}</a></h4></td>
        <td><a href="/category/{{rs.category.id}}/{{rs.category.slug}}">{{rs.product.category}}</a></td>
        <td><h4>{{rs.product.price}}TL</h4></td>
        <td><h4>{{rs.quantity}}</h4></td>
        <td><h4>{{rs.amount}}TL</h4></td>
        <td><a href="/order/deletefromcart/{{ rs.id }}" onclick="return confirm('Are you sure?')"><i class="fa fa-close"></i> </a> </td>
    </tr>

    {% endfor %}
    <tfoot>
        <tr>
            <th class="empty" colspan="4"></th>
            <th>TOTAL</th>
            <th>{{total}}TL</th>
        </tr>

    </tfoot>
</table>
</section>
<h6 class=" center-text"><a href="/order/orderproduct" class="btn-primaryc plr-25"><b> ORDER</b></a></h6>

<hr>
{% endblock %}